name: Deploy to Fly.io

on:
  push:
    branches:
      - master # Troque para sua branch se não for "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@v1
        with:
          args: "deploy"

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
